
import os
import json
import time
import requests
import threading
from datetime import datetime

# --- Config ---
client_id = os.environ.get("X_CLIENT_ID")
client_secret = os.environ.get("X_CLIENT_SECRET")

MEMORY_FILE = "memory.json"
MEMORY_LOCK = threading.Lock()

# --- Memory Sync ---

def load_memory():
    """Load shared memory from disk, thread-safe."""
    with MEMORY_LOCK:
        try:
            if os.path.exists(MEMORY_FILE):
                with open(MEMORY_FILE, "r") as f:
                    return json.load(f)
        except (json.JSONDecodeError, IOError):
            pass
        return {"agents": {}, "assets": [], "events": [], "last_updated": None}

def save_memory(memory):
    """Persist shared memory to disk, thread-safe."""
    with MEMORY_LOCK:
        memory["last_updated"] = datetime.utcnow().isoformat()
        with open(MEMORY_FILE, "w") as f:
            json.dump(memory, f, indent=2)

def update_agent_memory(agent_id, state: dict):
    """
    Sync an individual agent's state into shared memory.
    This ensures memory updates and asset generation stay in sync.
    """
    memory = load_memory()
    if "agents" not in memory:
        memory["agents"] = {}
    memory["agents"][agent_id] = {
        "state": state,
        "updated_at": datetime.utcnow().isoformat()
    }
    save_memory(memory)
    return memory

def register_asset(agent_id, asset: dict):
    """
    Register a generated asset in shared memory, linked to the agent.
    Ensures asset generation is recorded in sync with memory state.
    """
    memory = load_memory()
    if "assets" not in memory:
        memory["assets"] = []
    asset_entry = {
        "agent_id": agent_id,
        "asset": asset,
        "created_at": datetime.utcnow().isoformat()
    }
    memory["assets"].append(asset_entry)
    # Also update agent's last asset timestamp for sync tracking
    if "agents" in memory and agent_id in memory["agents"]:
        memory["agents"][agent_id]["last_asset_at"] = asset_entry["created_at"]
    save_memory(memory)
    return asset_entry

def log_event(agent_id, event_type, details=None):
    """Log an event for an agent into shared memory."""
    memory = load_memory()
    if "events" not in memory:
        memory["events"] = []
    event = {
        "agent_id": agent_id,
        "event_type": event_type,
        "details": details or {},
        "timestamp": datetime.utcnow().isoformat()
    }
    memory["events"].append(event)
    # Keep only last 500 events to prevent unbounded growth
    if len(memory["events"]) > 500:
        memory["events"] = memory["events"][-500:]
    save_memory(memory)
    return event

def get_all_agent_states():
    """Return current state of all agents from shared memory."""
    memory = load_memory()
    return memory.get("agents", {})

def get_assets_for_agent(agent_id):
    """Return all assets generated by a specific agent."""
    memory = load_memory()
    return [
        entry for entry in memory.get("assets", [])
        if entry.get("agent_id") == agent_id
    ]

def sync_network_state(agent_states: dict):
    """
    Bulk-sync all 9 agents' states into memory atomically.
    Prevents partial updates that cause memory/asset generation desync.
    """
    memory = load_memory()
    if "agents" not in memory:
        memory["agents"] = {}
    now = datetime.utcnow().isoformat()
    for agent_id, state in agent_states.items():
        memory["agents"][agent_id] = {
            "state": state,
            "updated_at": now
        }
    save_memory(memory)
    return memory

# --- X (Twitter) Posting ---

def post_to_x(text_content):
    if not client_id or not client_secret:
        return "Skipped (Missing X Secrets)"
    
    try:
        token_url = "https://api.x.com/2/oauth2/token"
        auth_data = {
            "grant_type": "client_credentials",
            "client_id": client_id,
            "client_secret": client_secret,
            "client_type": "public"
        }
        headers = {
            "Content-Type": "application/x-www-form-urlencoded"
        }
        response = requests.post(token_url, data=auth_data, headers=headers)
        
        if response.status_code != 200:
            return f"Auth Failed: {response.text}"
            
        token_json = response.json()
        access_token = token_json.get("access_token")
        
        if not access_token:
            return "Auth Failed: No access token returned"
            
        tweet_url = "https://api.x.com/2/tweets"
        tweet_headers = {
            "Authorization": f"Bearer {access_token}",
            "Content-Type": "application/json"
        }
        payload = {"text": text_content}
        
        tweet_response = requests.post(tweet_url, headers=tweet_headers, json=payload)
        if tweet_response.status_code == 201:
            return "Successfully Posted Live!"
        else:
            return f"Post Failed: {tweet_response.status_code} - {tweet_response.text}"
            
    except Exception as e:
        return f"Error: {str(e)}"
