{
  "mcpServers": {
    "tavily": {
      "command": "npx",
      "args": [
        "-y",
        "mcp-remote",
        "https://mcp.tavily.com/mcp/?tavilyApiKey=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"
      ]
    }
  }
}
